apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sisvan

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: sisvan-dashboard
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: sisvan

images:
  - name: sisvan-dashboard
    newTag: latest
