apiVersion: v1
kind: Service
metadata:
  name: sisvan-dashboard-service
  labels:
    app: sisvan-dashboard
spec:
  type: ClusterIP
  selector:
    app: sisvan-dashboard
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
